include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable rules that cause too many warnings/info issues
    prefer_const_constructors: false
    unnecessary_brace_in_string_interps: false

